### ISSUE TITLE
How does this work? For what purpose?

### ISSUE THREAD

**Issue by tongliye** [Zvendson/GwFileServer-Client#1]
How does this work? For what purpose?

**Comment by Zvendson** [comment]
> How does this work? For what purpose?

Hej, Sorry im currently not home for a month but this is supposed to be client example to connect to the GW File Server and download any file by its FileID.

I actually forgot to rename the project to "Client" than "Server".
I think i already continued on this project but wont be home for another Month.

Just clone it and build it with VS17 or higher

**Comment by Zvendson** [comment]
Just updated the project with a README. feel free to re-check it
